### ISSUE TITLE
Refactor KE code (maybe rewrite in python)

### ISSUE THREAD

**Issue by nmarks99** [NUSTARS/launch-vehicle#1]
It should be made so that the code is **extremely**  easy to use since the code itself and the goals of it are simple. The best solution would probably be to rewrite the code in python and make a CLI for it. It should be lighting fast to use and execute.

**Comment by thereal-adubs** [comment]
Moving all simple hand-calcs like fin flutter, terminal velocity, and kinetic energy calculation to spreadsheets for future design cycles. Using updated script RecoveryDynamics.m to capture full transient behavior of parachute events.
